fix: define repository types
kubebb/core pull request #110
Opened 2023-07-16 13:16 UTC by 0xff-dev

fix: define repository types
Maybe Fix: https://github.com/kubebb/core/issues/103

2023-07-16 15:08 UTC, bjwswang approved these changes

2023-07-16 15:13 UTC, bjwswang commented
@0xff-dev Great! We need to define the repository types later.

2023-07-16 17:23 UTC, Abirdcfly requested changes
May need change example test

2023-07-17 07:06 UTC, bjwswang commented
@Abirdcfly unit tests failed in `helm` package

2023-07-17 07:06 UTC, merged