feat: componentplan controller add event logic
kubebb/core pull request #135
Opened 2023-07-19 06:11 UTC by 0xff-dev

feat: componentplan controller add event logic
Fix: https://github.com/kubebb/core/issues/64

2023-07-19 08:37 UTC, Abirdcfly commented
some test failed due to other issue, will be fixed by #124, may hold on this pr until #124 is merged.😳

2023-07-20 02:45 UTC, bjwswang requested changes

2023-07-20 08:54 UTC, Abirdcfly approved these changes

2023-07-20 11:01 UTC, bjwswang approved these changes

2023-07-20 11:01 UTC, merged