feat: develop a pipeline for rating
kubebb/core pull request #159
Opened 2023-07-25 07:37 UTC by 0xff-dev

feat: develop a pipeline for rating

2023-07-25 07:48 UTC, Abirdcfly commented on pipeline/task-helm-lint.yaml
> +        curl -LO $(params.url)
helm pull?

2023-07-25 07:49 UTC, Abirdcfly commented on pipeline/task-rbac.yaml
> +        cat base.json|jq --arg dot "$(cat r.dot |base64)" '.binaryData.r = $dot' | jq --arg name "$NAME" '.metadata.name = $name' | jq --arg namespace "$NAMESPACE" '.metadata.namespace = $namespace'
what about use kubectl command?

2023-07-25 07:50 UTC, bjwswang requested changes
1. places these under directory `pipeline/rating/xxx`
2. make `pipeline-run.yaml` under `pipeline/rating/samples` like https://github.com/bestchains/installer/tree/main/fabric-operator/tekton/pipelines

2023-07-25 07:55 UTC, bjwswang commented on pipeline/pipeline-run.yaml
> +  labels:
1. should add some labels to indicate which `component`  and `repository` this pipeline is for.
2. should add annotations to indciate this is for `kubebb rating`

2023-07-25 07:57 UTC, bjwswang requested changes
besides... please add a document

2023-07-26 01:37 UTC, Abirdcfly approved these changes

2023-07-26 01:37 UTC, Abirdcfly commented on pipeline/rating/tasks/task-helm-lint.yaml
> +        tar -zxvf $(params.component)-$(params.version).tgz
use `--untar`?
`--untar                      if set to true, will untar the chart after downloading it`

2023-07-26 08:46 UTC, bjwswang commented on pipeline/rating/pipeline.yaml
> +    - name: helm-lint
Do `helm lint` in front of `rback`

2023-07-26 08:49 UTC, bjwswang commented on pipeline/rating/tasks/task-helm-lint.yaml
> +      image: kubebb/component-rbac-lint:v0.0.1
Since there would be many task besides `rback` and `lint`, `kubebb/component-rating` would be much better

2023-07-26 08:52 UTC, bjwswang commented on pipeline/rating/Dockerfile
> +COPY helm /usr/local/bin
where to find `helm` `yq`?

2023-07-26 09:41 UTC, Abirdcfly commented on pipeline/rating/Dockerfile
> +    wget https://github.com/mikefarah/yq/releases/download/$VERSION/$BINARY.tar.gz -O - |\
see https://pkgs.alpinelinux.org/package/edge/community/x86/helm and https://pkgs.alpinelinux.org/package/edge/community/x86/yq, I guess we can just `apk add yq helm`

2023-07-26 09:54 UTC, Abirdcfly commented on pipeline/rating/Dockerfile
> +    wget https://github.com/mikefarah/yq/releases/download/$VERSION/$BINARY.tar.gz -O - |\
https://github.com/alpine-docker/k8s just use this docker image. It has everything we need!

2023-07-27 01:53 UTC, bjwswang approved these changes

2023-07-27 01:53 UTC, merged