feat: add example-test for rating
kubebb/core pull request #299
Opened 2023-08-25 08:33 UTC by 0xff-dev

#### What type of PR is this?
/kind feature

#### What this PR does / why we need it
feat: add example-test for rating

#### Which issue(s) this PR fixes

Fix: https://github.com/kubebb/core/issues/293

#### Special notes for your reviewer
https://github.com/0xff-dev/core/actions/runs/5973617083/job/16206305101

2023-08-25 09:19 UTC, Abirdcfly approved these changes

2023-08-25 09:19 UTC, Abirdcfly commented on config/samples/tekton_test.sh
> +		versions=$(kubectl -n${namespace} get components.core.kubebb.k8s.com.cn ${componentName} -ojson | jq -r '.status.versions|length')
--ignore-not-found=true

2023-08-25 09:19 UTC, Abirdcfly commented on config/samples/tekton_test.sh
> +			#			digest=$(kubectl -n${namespace} get components.core.kubebb.k8s.com.cn ${componentName} -ojson | jq -r '.status.versions.digest')
remove this comment

2023-08-25 09:19 UTC, Abirdcfly commented on config/samples/tekton_test.sh
> +		complete=$(kubectl -n${namespace} get rating ${ratingName} -ojson | jq '.status.pipelineRuns' | jq '{l:length,o:map(select(.conditions[0].type=="Succeeded" and .conditions[0].status=="True"))|lengt
--ignore-not-found=true

2023-08-25 09:19 UTC, Abirdcfly commented on config/samples/tekton_test.sh
> +		cm=$(kubectl -n${namespace} get cm ${cmname} -ojson | jq -r '.metadata.name')
--ignore-not-found=true

2023-08-29 01:30 UTC, Abirdcfly approved these changes

2023-08-29 01:30 UTC, Abirdcfly commented on config/samples/tekton_test.sh
> +LOG_DIR=${LOG_DIR:-"/tmp/kubebb-core-example-test/logs"}
kubebb-core-tekton-test

2023-08-29 06:23 UTC, bjwswang commented on .github/workflows/example_test.yaml
> +  tekton-test:
`tekton-test` ->  `rating-test`

2023-08-29 06:23 UTC, bjwswang commented on config/samples/tekton_test.sh
> +#!/bin/bash
tekton-test -> rating-test

2023-08-29 06:24 UTC, bjwswang requested changes
tekton -> rating

2023-08-29 08:42 UTC, bjwswang approved these changes

2023-08-29 08:42 UTC, merged